### PR TITLE
Improve Admin dashboard user interface

### PR DESCRIPTION
**Pull request by Maimymai**
Dashboard-admin

### CODE REVIEW

**Review by Naqibullah-sediqi — COMMENTED** [review]
Please add the css code to css file. in here css code is inside html page which makes the code unreadable

**Review by haneeva — APPROVED** [review]
Label color needs to change after everything is completed. Just make color things so its not plain.

**Review by Naqibullah-sediqi — APPROVED** [review]
approved

**Review by Naqibullah-sediqi — APPROVED** [review]
approved

**Comment by mmafrar** [comment]
> Please add the css code to css file. in here css code is inside html page which makes the code unreadable

@Pravin030399 will work on this after merging in a new branch

**Review by mmafrar — APPROVED** [review]

**Pull request merged**
